### ISSUE TITLE
Clarificar quan username es nom o email

### ISSUE THREAD

**Issue by agnes-masip** [OFF-Home/off-home-back2.0#18]
Sprint 3 arreglar. Fiquem a tot arreu :username però a front es confonen de si es email o el nom. Sobretot perquè a usuaris :username és nom i en general a tot arreu és email.

**Comment by arnauboy** [comment]
a la branca de refactor poso que a usuaris comprovi el email

**Comment by arnauboy** [comment]
només he vist que necessités canvis el update usuaris, que agafava com a target el username

**Comment by arnauboy** [comment]
He canviat l'update usuari per a que comprovi amb l'email i no amb el nom d'usuari
